// <auto-generated />
using System;
using InvestigadorAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestigadorAPI.Migrations
{
    [DbContext(typeof(InvestigadorContext))]
    [Migration("20230902202114_initialdata")]
    partial class initialdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Investigador", b =>
                {
                    b.Property<Guid>("InvestigadorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Afiliacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvestigadorID");

                    b.ToTable("Investigador", (string)null);

                    b.HasData(
                        new
                        {
                            InvestigadorID = new Guid("82ea4c24-53f8-4648-a0e4-76c3faf03d90"),
                            Afiliacion = "Tiempo completo",
                            Apellido = "Raulez",
                            Nombre = "Raul",
                            Rol = "Lider"
                        });
                });

            modelBuilder.Entity("Proyecto", b =>
                {
                    b.Property<Guid>("proyectoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripción")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("lider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("proyectoID");

                    b.ToTable("Proyecto", (string)null);

                    b.HasData(
                        new
                        {
                            proyectoID = new Guid("82ea4c24-53f8-4648-a0e4-76c3faf03d91"),
                            area = "Ingenieria",
                            descripción = "Son latas",
                            fechaFin = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            fechaInicio = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            lider = "Raul",
                            nombre = "Las latas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
